### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [gipsonsa/Week_12_Authorization_Authentication#1]
It doesn't look like my login information is working on Heroku. Did you add forget to add the user to Heroku's database?

**Comment by chrisvfritz** [comment]
Any progress here?

**Comment by gipsonsa** [comment]
Oh I couldn’t find this first email, that explains my confusion. I’ll be sure this is completed this Monday.

**Comment by chrisvfritz** [comment]
Great! Just comment here when I should take another look.

**Comment by gipsonsa** [comment]
These should be fixed!
Thanks for the help in class!

**Comment by chrisvfritz** [comment]
:+1: Excellent!
